### ISSUE TITLE
Implement Evaluate

### ISSUE THREAD

**Issue by fwcd** [fwcd/kotlin-debug-adapter#33]
Let user dynamically evaluate expressions.

**Comment by YU5Z8X2CvH1fv4ep** [comment]
Friends, I like to use vscode to debug kotlin, evaluate expressions are very useful and necessary functions. Can the function be enhanced?

**Comment by YU5Z8X2CvH1fv4ep** [comment]
![adadad](https://user-images.githubusercontent.com/57204004/89900013-bc4fed00-dc15-11ea-91e4-f625280a5a27.png)


Cannot execute function
