### ISSUE TITLE
Fix issues with the shared module dependency and update it

### ISSUE THREAD

**Issue by tsal** [fwcd/kotlin-debug-adapter#74]
While there may be other issues, it looks like the only "fix" for this is to fully install Gradle and use that, instead of the wrapper. I don't know the specifics, but it appears it's related to composite builds and Gradle 7.x vs 8.x.

Unfortunately, Gradle's documentation is second only to Apple's in the "worst documentation on the planet" category.

**Comment by themkat** [comment]
Thanks for letting us know! ❤️ I have made a PR to briefly put out the fire and let the builds work again. The current fix is simply to hardcode the `kotlin-language-server` shared module version (it has not changed in a while, so probably okay). Not a good permanent solution, but something that will make this project work again... #75 . At least we put out this fire 🧯

**Comment by fwcd** [comment]
Hm, any thoughts what specifically caused this incompatibility and how we could update the language server side? Ideally we'd want to be able to update the shared module alongside the language server again...

**Comment by themkat** [comment]
The main issue is probably that the main language server uses Kotlin DSL these days and a WAY newer Gradle version. I think we can slowly move towards using the shared modue again after updating a bit here.

**Comment by themkat** [comment]
Hopefully this issue is now closed with #81 being merged 🙂 Re-open if that is not the case
