### ISSUE TITLE
Gradle dependencies could not be resolved [Kotlin VS Code Extension]

### ISSUE THREAD

**Issue by PaulTaykalo** [fwcd/kotlin-debug-adapter#78]
This repository has a dependency on the language server `shared` libs, which are mostly used for resolving classpaths for the tasks that will be lauched by adapter and the LSP server itself

Like Here:
https://github.com/fwcd/kotlin-language-server/blob/77ecc25718befa0dd0e31e0caaa95d29170aabd8/shared/src/main/kotlin/org/javacs/kt/classpath/GradleClassPathResolver.kt#L17

In order to resolve Gradle dependenies, `shared` lib would run `projectClassPathFinder.gradle` file, which is contained in the shared.jar

## Problem

**.gradle files are missing in the shared.jar lib** in 

Currently Built artifact 0.4.3 .zip 
https://github.com/fwcd/kotlin-debug-adapter/releases/tag/0.4.3

As well as  artifact that will be downloaded by the Kotlin Plugin for VSCode
<img width="564" alt="image" src="https://github.com/fwcd/kotlin-debug-adapter/assets/119268/24ab812a-50e5-4432-9fa2-278dd8db4c0b">

## Missing Resources
![image](https://github.com/fwcd/kotlin-debug-adapter/assets/119268/6a0191e9-32df-4ce5-9c19-fad23d156bf3)

## Expected Structure
![image](https://github.com/fwcd/kotlin-debug-adapter/assets/119268/b21737b8-509d-40ed-8a37-3891cbc53717)

## Actual result
When user will try to run debug adapter for vscode, they will receive an error (somewhat warning) that gradle dependencies could not be resolved
```
[WARN] async1    Could not resolve classpath using Gradle: ClassLoader.getSystemResourceAsStream(scriptName) must not be null
```

### Related issues

- https://stackoverflow.com/questions/75418906/how-to-configure-vscode-to-debug-a-gradle-kotlin-project
- https://github.com/fwcd/kotlin-debug-adapter/issues/69

## Suggested Solution

- [ ] Rebuild the current project, and make a release. 
- [ ] Check that needed files are located at the `shared.jar` inside of the artifact

Since VSCode Kotlin Extension downloads the latest version, no changes will be needed in the Kotlin Extension. (maybe files needed to be redownloaded, not sure)

## Workaround 

Build this repo manually and place the result in the VSCode  Kotlin Extension storage.

Hope this helps :)

**Comment by fwcd** [comment]
Nice find!

The issue is that [Jitpack](https://jitpack.io) (which the latest release 0.4.3 still uses for the dependency on the Kotlin language server's `shared` lib, see [`adapter/build.gradle`](https://github.com/fwcd/kotlin-debug-adapter/blob/655086d44a177bd306ff1ce498786f998f508c67/adapter/build.gradle#L20)) didn't seem to package up resources, unfortunately.

Nowadays the debug adapter uses a Gradle source dependency, which doesn't seem to have this issue, so releasing a new version will probably fix this. I'll see if I find some time to do so.

**Comment by tariqajyusuf** [comment]
Another one here having a similar issue :)
